//gomenasai :c

LUA->PushNumber(WM_ACTIVATE);
LUA->SetField(-2, "ACTIVATE");

LUA->PushNumber(WM_NULL);
LUA->SetField(-2, "NULL");

LUA->PushNumber(WM_ACTIVATEAPP);
LUA->SetField(-2, "ACTIVATEAPP");

LUA->PushNumber(WM_CREATE);
LUA->SetField(-2, "CREATE");

LUA->PushNumber(WM_AFXFIRST);
LUA->SetField(-2, "AFXFIRST");

LUA->PushNumber(WM_DESTROY);
LUA->SetField(-2, "DESTROY");

LUA->PushNumber(WM_AFXLAST);
LUA->SetField(-2, "AFXLAST");

LUA->PushNumber(WM_MOVE);
LUA->SetField(-2, "MOVE");

LUA->PushNumber(WM_APP);
LUA->SetField(-2, "APP");

LUA->PushNumber(WM_SIZE);
LUA->SetField(-2, "SIZE");

LUA->PushNumber(WM_APPCOMMAND);
LUA->SetField(-2, "APPCOMMAND");

LUA->PushNumber(WM_ACTIVATE);
LUA->SetField(-2, "ACTIVATE");

LUA->PushNumber(WM_ASKCBFORMATNAME);
LUA->SetField(-2, "ASKCBFORMATNAME");

LUA->PushNumber(WM_SETFOCUS);
LUA->SetField(-2, "SETFOCUS");

LUA->PushNumber(WM_CANCELJOURNAL);
LUA->SetField(-2, "CANCELJOURNAL");

LUA->PushNumber(WM_KILLFOCUS);
LUA->SetField(-2, "KILLFOCUS");

LUA->PushNumber(WM_CANCELMODE);
LUA->SetField(-2, "CANCELMODE");

LUA->PushNumber(WM_ENABLE);
LUA->SetField(-2, "ENABLE");

LUA->PushNumber(WM_CAPTURECHANGED);
LUA->SetField(-2, "CAPTURECHANGED");

LUA->PushNumber(WM_SETREDRAW);
LUA->SetField(-2, "SETREDRAW");

LUA->PushNumber(WM_CHANGECBCHAIN);
LUA->SetField(-2, "CHANGECBCHAIN");

LUA->PushNumber(WM_SETTEXT);
LUA->SetField(-2, "SETTEXT");

LUA->PushNumber(WM_CHANGEUISTATE);
LUA->SetField(-2, "CHANGEUISTATE");

LUA->PushNumber(WM_GETTEXT);
LUA->SetField(-2, "GETTEXT");

LUA->PushNumber(WM_CHAR);
LUA->SetField(-2, "CHAR");

LUA->PushNumber(WM_GETTEXTLENGTH);
LUA->SetField(-2, "GETTEXTLENGTH");

LUA->PushNumber(WM_CHARTOITEM);
LUA->SetField(-2, "CHARTOITEM");

LUA->PushNumber(WM_PAINT);
LUA->SetField(-2, "PAINT");

LUA->PushNumber(WM_CHILDACTIVATE);
LUA->SetField(-2, "CHILDACTIVATE");

LUA->PushNumber(WM_CLOSE);
LUA->SetField(-2, "CLOSE");

LUA->PushNumber(WM_CLEAR);
LUA->SetField(-2, "CLEAR");

LUA->PushNumber(WM_QUERYENDSESSION);
LUA->SetField(-2, "QUERYENDSESSION");

LUA->PushNumber(WM_CLOSE);
LUA->SetField(-2, "CLOSE");

LUA->PushNumber(WM_QUERYOPEN);
LUA->SetField(-2, "QUERYOPEN");

LUA->PushNumber(WM_COMMAND);
LUA->SetField(-2, "COMMAND");

LUA->PushNumber(WM_ENDSESSION);
LUA->SetField(-2, "ENDSESSION");

LUA->PushNumber(WM_COMMNOTIFY);
LUA->SetField(-2, "COMMNOTIFY");

LUA->PushNumber(WM_QUIT);
LUA->SetField(-2, "QUIT");

LUA->PushNumber(WM_COMPACTING);
LUA->SetField(-2, "COMPACTING");

LUA->PushNumber(WM_ERASEBKGND);
LUA->SetField(-2, "ERASEBKGND");

LUA->PushNumber(WM_COMPAREITEM);
LUA->SetField(-2, "COMPAREITEM");

LUA->PushNumber(WM_SYSCOLORCHANGE);
LUA->SetField(-2, "SYSCOLORCHANGE");

LUA->PushNumber(WM_CONTEXTMENU);
LUA->SetField(-2, "CONTEXTMENU");

LUA->PushNumber(WM_SHOWWINDOW);
LUA->SetField(-2, "SHOWWINDOW");

LUA->PushNumber(WM_COPY);
LUA->SetField(-2, "COPY");

LUA->PushNumber(WM_WININICHANGE);
LUA->SetField(-2, "WININICHANGE");

LUA->PushNumber(WM_COPYDATA);
LUA->SetField(-2, "COPYDATA");

LUA->PushNumber(WM_SETTINGCHANGE);
LUA->SetField(-2, "SETTINGCHANGE");

LUA->PushNumber(WM_CREATE);
LUA->SetField(-2, "CREATE");

LUA->PushNumber(WM_DEVMODECHANGE);
LUA->SetField(-2, "DEVMODECHANGE");

LUA->PushNumber(WM_CTLCOLORBTN);
LUA->SetField(-2, "CTLCOLORBTN");

LUA->PushNumber(WM_ACTIVATEAPP);
LUA->SetField(-2, "ACTIVATEAPP");

LUA->PushNumber(WM_CTLCOLORDLG);
LUA->SetField(-2, "CTLCOLORDLG");

LUA->PushNumber(WM_FONTCHANGE);
LUA->SetField(-2, "FONTCHANGE");

LUA->PushNumber(WM_CTLCOLOREDIT);
LUA->SetField(-2, "CTLCOLOREDIT");

LUA->PushNumber(WM_TIMECHANGE);
LUA->SetField(-2, "TIMECHANGE");

LUA->PushNumber(WM_CTLCOLORLISTBOX);
LUA->SetField(-2, "CTLCOLORLISTBOX");

LUA->PushNumber(WM_CANCELMODE);
LUA->SetField(-2, "CANCELMODE");

LUA->PushNumber(WM_CTLCOLORMSGBOX);
LUA->SetField(-2, "CTLCOLORMSGBOX");

LUA->PushNumber(WM_SETCURSOR);
LUA->SetField(-2, "SETCURSOR");

LUA->PushNumber(WM_CTLCOLORSCROLLBAR);
LUA->SetField(-2, "CTLCOLORSCROLLBAR");

LUA->PushNumber(WM_MOUSEACTIVATE);
LUA->SetField(-2, "MOUSEACTIVATE");

LUA->PushNumber(WM_CTLCOLORSTATIC);
LUA->SetField(-2, "CTLCOLORSTATIC");

LUA->PushNumber(WM_CHILDACTIVATE);
LUA->SetField(-2, "CHILDACTIVATE");

LUA->PushNumber(WM_CUT);
LUA->SetField(-2, "CUT");

LUA->PushNumber(WM_QUEUESYNC);
LUA->SetField(-2, "QUEUESYNC");

LUA->PushNumber(WM_DEADCHAR);
LUA->SetField(-2, "DEADCHAR");

LUA->PushNumber(WM_GETMINMAXINFO);
LUA->SetField(-2, "GETMINMAXINFO");

LUA->PushNumber(WM_DELETEITEM);
LUA->SetField(-2, "DELETEITEM");

LUA->PushNumber(WM_PAINTICON);
LUA->SetField(-2, "PAINTICON");

LUA->PushNumber(WM_DESTROY);
LUA->SetField(-2, "DESTROY");

LUA->PushNumber(WM_ICONERASEBKGND);
LUA->SetField(-2, "ICONERASEBKGND");

LUA->PushNumber(WM_DESTROYCLIPBOARD);
LUA->SetField(-2, "DESTROYCLIPBOARD");

LUA->PushNumber(WM_NEXTDLGCTL);
LUA->SetField(-2, "NEXTDLGCTL");

LUA->PushNumber(WM_DEVICECHANGE);
LUA->SetField(-2, "DEVICECHANGE");

LUA->PushNumber(WM_SPOOLERSTATUS);
LUA->SetField(-2, "SPOOLERSTATUS");

LUA->PushNumber(WM_DEVMODECHANGE);
LUA->SetField(-2, "DEVMODECHANGE");

LUA->PushNumber(WM_DRAWITEM);
LUA->SetField(-2, "DRAWITEM");

LUA->PushNumber(WM_DISPLAYCHANGE);
LUA->SetField(-2, "DISPLAYCHANGE");

LUA->PushNumber(WM_MEASUREITEM);
LUA->SetField(-2, "MEASUREITEM");

LUA->PushNumber(WM_DRAWCLIPBOARD);
LUA->SetField(-2, "DRAWCLIPBOARD");

LUA->PushNumber(WM_DELETEITEM);
LUA->SetField(-2, "DELETEITEM");

LUA->PushNumber(WM_DRAWITEM);
LUA->SetField(-2, "DRAWITEM");

LUA->PushNumber(WM_VKEYTOITEM);
LUA->SetField(-2, "VKEYTOITEM");

LUA->PushNumber(WM_DROPFILES);
LUA->SetField(-2, "DROPFILES");

LUA->PushNumber(WM_CHARTOITEM);
LUA->SetField(-2, "CHARTOITEM");

LUA->PushNumber(WM_ENABLE);
LUA->SetField(-2, "ENABLE");

LUA->PushNumber(WM_SETFONT);
LUA->SetField(-2, "SETFONT");

LUA->PushNumber(WM_ENDSESSION);
LUA->SetField(-2, "ENDSESSION");

LUA->PushNumber(WM_GETFONT);
LUA->SetField(-2, "GETFONT");

LUA->PushNumber(WM_ENTERIDLE);
LUA->SetField(-2, "ENTERIDLE");

LUA->PushNumber(WM_SETHOTKEY);
LUA->SetField(-2, "SETHOTKEY");

LUA->PushNumber(WM_ENTERMENULOOP);
LUA->SetField(-2, "ENTERMENULOOP");

LUA->PushNumber(WM_GETHOTKEY);
LUA->SetField(-2, "GETHOTKEY");

LUA->PushNumber(WM_ENTERSIZEMOVE);
LUA->SetField(-2, "ENTERSIZEMOVE");

LUA->PushNumber(WM_QUERYDRAGICON);
LUA->SetField(-2, "QUERYDRAGICON");

LUA->PushNumber(WM_ERASEBKGND);
LUA->SetField(-2, "ERASEBKGND");

LUA->PushNumber(WM_COMPAREITEM);
LUA->SetField(-2, "COMPAREITEM");

LUA->PushNumber(WM_EXITMENULOOP);
LUA->SetField(-2, "EXITMENULOOP");

LUA->PushNumber(WM_GETOBJECT);
LUA->SetField(-2, "GETOBJECT");

LUA->PushNumber(WM_EXITSIZEMOVE);
LUA->SetField(-2, "EXITSIZEMOVE");

LUA->PushNumber(WM_COMPACTING);
LUA->SetField(-2, "COMPACTING");

LUA->PushNumber(WM_FONTCHANGE);
LUA->SetField(-2, "FONTCHANGE");

LUA->PushNumber(WM_COMMNOTIFY);
LUA->SetField(-2, "COMMNOTIFY");

LUA->PushNumber(WM_GETDLGCODE);
LUA->SetField(-2, "GETDLGCODE");

LUA->PushNumber(WM_WINDOWPOSCHANGING);
LUA->SetField(-2, "WINDOWPOSCHANGING");

LUA->PushNumber(WM_GETFONT);
LUA->SetField(-2, "GETFONT");

LUA->PushNumber(WM_WINDOWPOSCHANGED);
LUA->SetField(-2, "WINDOWPOSCHANGED");

LUA->PushNumber(WM_GETHOTKEY);
LUA->SetField(-2, "GETHOTKEY");

LUA->PushNumber(WM_POWER);
LUA->SetField(-2, "POWER");

LUA->PushNumber(WM_GETICON);
LUA->SetField(-2, "GETICON");

LUA->PushNumber(WM_COPYDATA);
LUA->SetField(-2, "COPYDATA");

LUA->PushNumber(WM_GETMINMAXINFO);
LUA->SetField(-2, "GETMINMAXINFO");

LUA->PushNumber(WM_CANCELJOURNAL);
LUA->SetField(-2, "CANCELJOURNAL");

LUA->PushNumber(WM_GETOBJECT);
LUA->SetField(-2, "GETOBJECT");

LUA->PushNumber(WM_NOTIFY);
LUA->SetField(-2, "NOTIFY");

LUA->PushNumber(WM_GETTEXT);
LUA->SetField(-2, "GETTEXT");

LUA->PushNumber(WM_INPUTLANGCHANGEREQUEST);
LUA->SetField(-2, "INPUTLANGCHANGEREQUEST");

LUA->PushNumber(WM_GETTEXTLENGTH);
LUA->SetField(-2, "GETTEXTLENGTH");

LUA->PushNumber(WM_INPUTLANGCHANGE);
LUA->SetField(-2, "INPUTLANGCHANGE");

LUA->PushNumber(WM_HANDHELDFIRST);
LUA->SetField(-2, "HANDHELDFIRST");

LUA->PushNumber(WM_TCARD);
LUA->SetField(-2, "TCARD");

LUA->PushNumber(WM_HANDHELDLAST);
LUA->SetField(-2, "HANDHELDLAST");

LUA->PushNumber(WM_HELP);
LUA->SetField(-2, "HELP");

LUA->PushNumber(WM_HELP);
LUA->SetField(-2, "HELP");

LUA->PushNumber(WM_USERCHANGED);
LUA->SetField(-2, "USERCHANGED");

LUA->PushNumber(WM_HOTKEY);
LUA->SetField(-2, "HOTKEY");

LUA->PushNumber(WM_NOTIFYFORMAT);
LUA->SetField(-2, "NOTIFYFORMAT");

LUA->PushNumber(WM_HSCROLL);
LUA->SetField(-2, "HSCROLL");

LUA->PushNumber(WM_CONTEXTMENU);
LUA->SetField(-2, "CONTEXTMENU");

LUA->PushNumber(WM_HSCROLLCLIPBOARD);
LUA->SetField(-2, "HSCROLLCLIPBOARD");

LUA->PushNumber(WM_STYLECHANGING);
LUA->SetField(-2, "STYLECHANGING");

LUA->PushNumber(WM_ICONERASEBKGND);
LUA->SetField(-2, "ICONERASEBKGND");

LUA->PushNumber(WM_STYLECHANGED);
LUA->SetField(-2, "STYLECHANGED");

LUA->PushNumber(WM_IME_CHAR);
LUA->SetField(-2, "IME_CHAR");

LUA->PushNumber(WM_DISPLAYCHANGE);
LUA->SetField(-2, "DISPLAYCHANGE");

LUA->PushNumber(WM_IME_COMPOSITION);
LUA->SetField(-2, "IME_COMPOSITION");

LUA->PushNumber(WM_GETICON);
LUA->SetField(-2, "GETICON");

LUA->PushNumber(WM_IME_COMPOSITIONFULL);
LUA->SetField(-2, "IME_COMPOSITIONFULL");

LUA->PushNumber(WM_SETICON);
LUA->SetField(-2, "SETICON");

LUA->PushNumber(WM_IME_CONTROL);
LUA->SetField(-2, "IME_CONTROL");

LUA->PushNumber(WM_NCCREATE);
LUA->SetField(-2, "NCCREATE");

LUA->PushNumber(WM_IME_ENDCOMPOSITION);
LUA->SetField(-2, "IME_ENDCOMPOSITION");

LUA->PushNumber(WM_NCDESTROY);
LUA->SetField(-2, "NCDESTROY");

LUA->PushNumber(WM_IME_KEYDOWN);
LUA->SetField(-2, "IME_KEYDOWN");

LUA->PushNumber(WM_NCCALCSIZE);
LUA->SetField(-2, "NCCALCSIZE");

LUA->PushNumber(WM_IME_KEYLAST);
LUA->SetField(-2, "IME_KEYLAST");

LUA->PushNumber(WM_NCHITTEST);
LUA->SetField(-2, "NCHITTEST");

LUA->PushNumber(WM_IME_KEYUP);
LUA->SetField(-2, "IME_KEYUP");

LUA->PushNumber(WM_NCPAINT);
LUA->SetField(-2, "NCPAINT");

LUA->PushNumber(WM_IME_NOTIFY);
LUA->SetField(-2, "IME_NOTIFY");

LUA->PushNumber(WM_NCACTIVATE);
LUA->SetField(-2, "NCACTIVATE");

LUA->PushNumber(WM_IME_REQUEST);
LUA->SetField(-2, "IME_REQUEST");

LUA->PushNumber(WM_GETDLGCODE);
LUA->SetField(-2, "GETDLGCODE");

LUA->PushNumber(WM_IME_SELECT);
LUA->SetField(-2, "IME_SELECT");

LUA->PushNumber(WM_SYNCPAINT);
LUA->SetField(-2, "SYNCPAINT");

LUA->PushNumber(WM_IME_SETCONTEXT);
LUA->SetField(-2, "IME_SETCONTEXT");

LUA->PushNumber(WM_NCMOUSEMOVE);
LUA->SetField(-2, "NCMOUSEMOVE");

LUA->PushNumber(WM_IME_STARTCOMPOSITION);
LUA->SetField(-2, "IME_STARTCOMPOSITION");

LUA->PushNumber(WM_NCLBUTTONDOWN);
LUA->SetField(-2, "NCLBUTTONDOWN");

LUA->PushNumber(WM_INITDIALOG);
LUA->SetField(-2, "INITDIALOG");

LUA->PushNumber(WM_NCLBUTTONUP);
LUA->SetField(-2, "NCLBUTTONUP");

LUA->PushNumber(WM_INITMENU);
LUA->SetField(-2, "INITMENU");

LUA->PushNumber(WM_NCLBUTTONDBLCLK);
LUA->SetField(-2, "NCLBUTTONDBLCLK");

LUA->PushNumber(WM_INITMENUPOPUP);
LUA->SetField(-2, "INITMENUPOPUP");

LUA->PushNumber(WM_NCRBUTTONDOWN);
LUA->SetField(-2, "NCRBUTTONDOWN");

LUA->PushNumber(WM_INPUT);
LUA->SetField(-2, "INPUT");

LUA->PushNumber(WM_NCRBUTTONUP);
LUA->SetField(-2, "NCRBUTTONUP");

LUA->PushNumber(WM_INPUTLANGCHANGE);
LUA->SetField(-2, "INPUTLANGCHANGE");

LUA->PushNumber(WM_NCRBUTTONDBLCLK);
LUA->SetField(-2, "NCRBUTTONDBLCLK");

LUA->PushNumber(WM_INPUTLANGCHANGEREQUEST);
LUA->SetField(-2, "INPUTLANGCHANGEREQUEST");

LUA->PushNumber(WM_NCMBUTTONDOWN);
LUA->SetField(-2, "NCMBUTTONDOWN");

LUA->PushNumber(WM_KEYDOWN);
LUA->SetField(-2, "KEYDOWN");

LUA->PushNumber(WM_NCMBUTTONUP);
LUA->SetField(-2, "NCMBUTTONUP");

LUA->PushNumber(WM_KEYFIRST);
LUA->SetField(-2, "KEYFIRST");

LUA->PushNumber(WM_NCMBUTTONDBLCLK);
LUA->SetField(-2, "NCMBUTTONDBLCLK");

LUA->PushNumber(WM_KEYLAST);
LUA->SetField(-2, "KEYLAST");

LUA->PushNumber(WM_NCXBUTTONDOWN);
LUA->SetField(-2, "NCXBUTTONDOWN");

LUA->PushNumber(WM_KEYUP);
LUA->SetField(-2, "KEYUP");

LUA->PushNumber(WM_NCXBUTTONUP);
LUA->SetField(-2, "NCXBUTTONUP");

LUA->PushNumber(WM_KILLFOCUS);
LUA->SetField(-2, "KILLFOCUS");

LUA->PushNumber(WM_NCXBUTTONDBLCLK);
LUA->SetField(-2, "NCXBUTTONDBLCLK");

LUA->PushNumber(WM_LBUTTONDBLCLK);
LUA->SetField(-2, "LBUTTONDBLCLK");

LUA->PushNumber(WM_INPUT);
LUA->SetField(-2, "INPUT");

LUA->PushNumber(WM_LBUTTONDOWN);
LUA->SetField(-2, "LBUTTONDOWN");

LUA->PushNumber(WM_KEYFIRST);
LUA->SetField(-2, "KEYFIRST");

LUA->PushNumber(WM_LBUTTONUP);
LUA->SetField(-2, "LBUTTONUP");

LUA->PushNumber(WM_KEYDOWN);
LUA->SetField(-2, "KEYDOWN");

LUA->PushNumber(WM_MBUTTONDBLCLK);
LUA->SetField(-2, "MBUTTONDBLCLK");

LUA->PushNumber(WM_KEYUP);
LUA->SetField(-2, "KEYUP");

LUA->PushNumber(WM_MBUTTONDOWN);
LUA->SetField(-2, "MBUTTONDOWN");

LUA->PushNumber(WM_CHAR);
LUA->SetField(-2, "CHAR");

LUA->PushNumber(WM_MBUTTONUP);
LUA->SetField(-2, "MBUTTONUP");

LUA->PushNumber(WM_DEADCHAR);
LUA->SetField(-2, "DEADCHAR");

LUA->PushNumber(WM_MDIACTIVATE);
LUA->SetField(-2, "MDIACTIVATE");

LUA->PushNumber(WM_SYSKEYDOWN);
LUA->SetField(-2, "SYSKEYDOWN");

LUA->PushNumber(WM_MDICASCADE);
LUA->SetField(-2, "MDICASCADE");

LUA->PushNumber(WM_SYSKEYUP);
LUA->SetField(-2, "SYSKEYUP");

LUA->PushNumber(WM_MDICREATE);
LUA->SetField(-2, "MDICREATE");

LUA->PushNumber(WM_SYSCHAR);
LUA->SetField(-2, "SYSCHAR");

LUA->PushNumber(WM_MDIDESTROY);
LUA->SetField(-2, "MDIDESTROY");

LUA->PushNumber(WM_SYSDEADCHAR);
LUA->SetField(-2, "SYSDEADCHAR");

LUA->PushNumber(WM_MDIGETACTIVE);
LUA->SetField(-2, "MDIGETACTIVE");

LUA->PushNumber(WM_KEYLAST);
LUA->SetField(-2, "KEYLAST");

LUA->PushNumber(WM_MDIICONARRANGE);
LUA->SetField(-2, "MDIICONARRANGE");

LUA->PushNumber(WM_UNICHAR);
LUA->SetField(-2, "UNICHAR");

LUA->PushNumber(WM_MDIMAXIMIZE);
LUA->SetField(-2, "MDIMAXIMIZE");

LUA->PushNumber(WM_IME_STARTCOMPOSITION);
LUA->SetField(-2, "IME_STARTCOMPOSITION");

LUA->PushNumber(WM_MDINEXT);
LUA->SetField(-2, "MDINEXT");

LUA->PushNumber(WM_IME_ENDCOMPOSITION);
LUA->SetField(-2, "IME_ENDCOMPOSITION");

LUA->PushNumber(WM_MDIREFRESHMENU);
LUA->SetField(-2, "MDIREFRESHMENU");

LUA->PushNumber(WM_IME_COMPOSITION);
LUA->SetField(-2, "IME_COMPOSITION");

LUA->PushNumber(WM_MDIRESTORE);
LUA->SetField(-2, "MDIRESTORE");

LUA->PushNumber(WM_IME_KEYLAST);
LUA->SetField(-2, "IME_KEYLAST");

LUA->PushNumber(WM_MDISETMENU);
LUA->SetField(-2, "MDISETMENU");

LUA->PushNumber(WM_INITDIALOG);
LUA->SetField(-2, "INITDIALOG");

LUA->PushNumber(WM_MDITILE);
LUA->SetField(-2, "MDITILE");

LUA->PushNumber(WM_COMMAND);
LUA->SetField(-2, "COMMAND");

LUA->PushNumber(WM_MEASUREITEM);
LUA->SetField(-2, "MEASUREITEM");

LUA->PushNumber(WM_SYSCOMMAND);
LUA->SetField(-2, "SYSCOMMAND");

LUA->PushNumber(WM_MENUCHAR);
LUA->SetField(-2, "MENUCHAR");

LUA->PushNumber(WM_TIMER);
LUA->SetField(-2, "TIMER");

LUA->PushNumber(WM_MENUCOMMAND);
LUA->SetField(-2, "MENUCOMMAND");

LUA->PushNumber(WM_HSCROLL);
LUA->SetField(-2, "HSCROLL");

LUA->PushNumber(WM_MENUDRAG);
LUA->SetField(-2, "MENUDRAG");

LUA->PushNumber(WM_VSCROLL);
LUA->SetField(-2, "VSCROLL");

LUA->PushNumber(WM_MENUGETOBJECT);
LUA->SetField(-2, "MENUGETOBJECT");

LUA->PushNumber(WM_INITMENU);
LUA->SetField(-2, "INITMENU");

LUA->PushNumber(WM_MENURBUTTONUP);
LUA->SetField(-2, "MENURBUTTONUP");

LUA->PushNumber(WM_INITMENUPOPUP);
LUA->SetField(-2, "INITMENUPOPUP");

LUA->PushNumber(WM_MENUSELECT);
LUA->SetField(-2, "MENUSELECT");

LUA->PushNumber(WM_MENUSELECT);
LUA->SetField(-2, "MENUSELECT");

LUA->PushNumber(WM_MOUSEACTIVATE);
LUA->SetField(-2, "MOUSEACTIVATE");

LUA->PushNumber(WM_MENUCHAR);
LUA->SetField(-2, "MENUCHAR");

LUA->PushNumber(WM_MOUSEFIRST);
LUA->SetField(-2, "MOUSEFIRST");

LUA->PushNumber(WM_ENTERIDLE);
LUA->SetField(-2, "ENTERIDLE");

LUA->PushNumber(WM_MOUSEHOVER);
LUA->SetField(-2, "MOUSEHOVER");

LUA->PushNumber(WM_MENURBUTTONUP);
LUA->SetField(-2, "MENURBUTTONUP");

LUA->PushNumber(WM_MOUSELAST);
LUA->SetField(-2, "MOUSELAST");

LUA->PushNumber(WM_MENUDRAG);
LUA->SetField(-2, "MENUDRAG");

LUA->PushNumber(WM_MOUSELAST);
LUA->SetField(-2, "MOUSELAST");

LUA->PushNumber(WM_MENUGETOBJECT);
LUA->SetField(-2, "MENUGETOBJECT");

LUA->PushNumber(WM_MOUSELAST);
LUA->SetField(-2, "MOUSELAST");

LUA->PushNumber(WM_UNINITMENUPOPUP);
LUA->SetField(-2, "UNINITMENUPOPUP");

LUA->PushNumber(WM_MOUSELEAVE);
LUA->SetField(-2, "MOUSELEAVE");

LUA->PushNumber(WM_MENUCOMMAND);
LUA->SetField(-2, "MENUCOMMAND");

LUA->PushNumber(WM_MOUSEMOVE);
LUA->SetField(-2, "MOUSEMOVE");

LUA->PushNumber(WM_CHANGEUISTATE);
LUA->SetField(-2, "CHANGEUISTATE");

LUA->PushNumber(WM_MOUSEWHEEL);
LUA->SetField(-2, "MOUSEWHEEL");

LUA->PushNumber(WM_UPDATEUISTATE);
LUA->SetField(-2, "UPDATEUISTATE");

LUA->PushNumber(WM_MOVE);
LUA->SetField(-2, "MOVE");

LUA->PushNumber(WM_QUERYUISTATE);
LUA->SetField(-2, "QUERYUISTATE");

LUA->PushNumber(WM_MOVING);
LUA->SetField(-2, "MOVING");

LUA->PushNumber(WM_CTLCOLORMSGBOX);
LUA->SetField(-2, "CTLCOLORMSGBOX");

LUA->PushNumber(WM_NCACTIVATE);
LUA->SetField(-2, "NCACTIVATE");

LUA->PushNumber(WM_CTLCOLOREDIT);
LUA->SetField(-2, "CTLCOLOREDIT");

LUA->PushNumber(WM_NCCALCSIZE);
LUA->SetField(-2, "NCCALCSIZE");

LUA->PushNumber(WM_CTLCOLORLISTBOX);
LUA->SetField(-2, "CTLCOLORLISTBOX");

LUA->PushNumber(WM_NCCREATE);
LUA->SetField(-2, "NCCREATE");

LUA->PushNumber(WM_CTLCOLORBTN);
LUA->SetField(-2, "CTLCOLORBTN");

LUA->PushNumber(WM_NCDESTROY);
LUA->SetField(-2, "NCDESTROY");

LUA->PushNumber(WM_CTLCOLORDLG);
LUA->SetField(-2, "CTLCOLORDLG");

LUA->PushNumber(WM_NCHITTEST);
LUA->SetField(-2, "NCHITTEST");

LUA->PushNumber(WM_CTLCOLORSCROLLBAR);
LUA->SetField(-2, "CTLCOLORSCROLLBAR");

LUA->PushNumber(WM_NCLBUTTONDBLCLK);
LUA->SetField(-2, "NCLBUTTONDBLCLK");

LUA->PushNumber(WM_CTLCOLORSTATIC);
LUA->SetField(-2, "CTLCOLORSTATIC");

LUA->PushNumber(WM_NCLBUTTONDOWN);
LUA->SetField(-2, "NCLBUTTONDOWN");

LUA->PushNumber(WM_MOUSEFIRST);
LUA->SetField(-2, "MOUSEFIRST");

LUA->PushNumber(WM_NCLBUTTONUP);
LUA->SetField(-2, "NCLBUTTONUP");

LUA->PushNumber(WM_MOUSEMOVE);
LUA->SetField(-2, "MOUSEMOVE");

LUA->PushNumber(WM_NCMBUTTONDBLCLK);
LUA->SetField(-2, "NCMBUTTONDBLCLK");

LUA->PushNumber(WM_LBUTTONDOWN);
LUA->SetField(-2, "LBUTTONDOWN");

LUA->PushNumber(WM_NCMBUTTONDOWN);
LUA->SetField(-2, "NCMBUTTONDOWN");

LUA->PushNumber(WM_LBUTTONUP);
LUA->SetField(-2, "LBUTTONUP");

LUA->PushNumber(WM_NCMBUTTONUP);
LUA->SetField(-2, "NCMBUTTONUP");

LUA->PushNumber(WM_LBUTTONDBLCLK);
LUA->SetField(-2, "LBUTTONDBLCLK");

LUA->PushNumber(WM_NCMOUSEHOVER);
LUA->SetField(-2, "NCMOUSEHOVER");

LUA->PushNumber(WM_RBUTTONDOWN);
LUA->SetField(-2, "RBUTTONDOWN");

LUA->PushNumber(WM_NCMOUSELEAVE);
LUA->SetField(-2, "NCMOUSELEAVE");

LUA->PushNumber(WM_RBUTTONUP);
LUA->SetField(-2, "RBUTTONUP");

LUA->PushNumber(WM_NCMOUSEMOVE);
LUA->SetField(-2, "NCMOUSEMOVE");

LUA->PushNumber(WM_RBUTTONDBLCLK);
LUA->SetField(-2, "RBUTTONDBLCLK");

LUA->PushNumber(WM_NCPAINT);
LUA->SetField(-2, "NCPAINT");

LUA->PushNumber(WM_MBUTTONDOWN);
LUA->SetField(-2, "MBUTTONDOWN");

LUA->PushNumber(WM_NCRBUTTONDBLCLK);
LUA->SetField(-2, "NCRBUTTONDBLCLK");

LUA->PushNumber(WM_MBUTTONUP);
LUA->SetField(-2, "MBUTTONUP");

LUA->PushNumber(WM_NCRBUTTONDOWN);
LUA->SetField(-2, "NCRBUTTONDOWN");

LUA->PushNumber(WM_MBUTTONDBLCLK);
LUA->SetField(-2, "MBUTTONDBLCLK");

LUA->PushNumber(WM_NCRBUTTONUP);
LUA->SetField(-2, "NCRBUTTONUP");

LUA->PushNumber(WM_MOUSELAST);
LUA->SetField(-2, "MOUSELAST");

LUA->PushNumber(WM_NCXBUTTONDBLCLK);
LUA->SetField(-2, "NCXBUTTONDBLCLK");

LUA->PushNumber(WM_MOUSEWHEEL);
LUA->SetField(-2, "MOUSEWHEEL");

LUA->PushNumber(WM_NCXBUTTONDOWN);
LUA->SetField(-2, "NCXBUTTONDOWN");

LUA->PushNumber(WM_MOUSELAST);
LUA->SetField(-2, "MOUSELAST");

LUA->PushNumber(WM_NCXBUTTONUP);
LUA->SetField(-2, "NCXBUTTONUP");

LUA->PushNumber(WM_XBUTTONDOWN);
LUA->SetField(-2, "XBUTTONDOWN");

LUA->PushNumber(WM_NEXTDLGCTL);
LUA->SetField(-2, "NEXTDLGCTL");

LUA->PushNumber(WM_XBUTTONUP);
LUA->SetField(-2, "XBUTTONUP");

LUA->PushNumber(WM_NEXTMENU);
LUA->SetField(-2, "NEXTMENU");

LUA->PushNumber(WM_XBUTTONDBLCLK);
LUA->SetField(-2, "XBUTTONDBLCLK");

LUA->PushNumber(WM_NOTIFY);
LUA->SetField(-2, "NOTIFY");

LUA->PushNumber(WM_MOUSELAST);
LUA->SetField(-2, "MOUSELAST");

LUA->PushNumber(WM_NOTIFYFORMAT);
LUA->SetField(-2, "NOTIFYFORMAT");

LUA->PushNumber(WM_PARENTNOTIFY);
LUA->SetField(-2, "PARENTNOTIFY");

LUA->PushNumber(WM_NULL);
LUA->SetField(-2, "NULL");

LUA->PushNumber(WM_ENTERMENULOOP);
LUA->SetField(-2, "ENTERMENULOOP");

LUA->PushNumber(WM_PAINT);
LUA->SetField(-2, "PAINT");

LUA->PushNumber(WM_EXITMENULOOP);
LUA->SetField(-2, "EXITMENULOOP");

LUA->PushNumber(WM_PAINTCLIPBOARD);
LUA->SetField(-2, "PAINTCLIPBOARD");

LUA->PushNumber(WM_NEXTMENU);
LUA->SetField(-2, "NEXTMENU");

LUA->PushNumber(WM_PAINTICON);
LUA->SetField(-2, "PAINTICON");

LUA->PushNumber(WM_SIZING);
LUA->SetField(-2, "SIZING");

LUA->PushNumber(WM_PALETTECHANGED);
LUA->SetField(-2, "PALETTECHANGED");

LUA->PushNumber(WM_CAPTURECHANGED);
LUA->SetField(-2, "CAPTURECHANGED");

LUA->PushNumber(WM_PALETTEISCHANGING);
LUA->SetField(-2, "PALETTEISCHANGING");

LUA->PushNumber(WM_MOVING);
LUA->SetField(-2, "MOVING");

LUA->PushNumber(WM_PARENTNOTIFY);
LUA->SetField(-2, "PARENTNOTIFY");

LUA->PushNumber(WM_POWERBROADCAST);
LUA->SetField(-2, "POWERBROADCAST");

LUA->PushNumber(WM_PASTE);
LUA->SetField(-2, "PASTE");

LUA->PushNumber(WM_DEVICECHANGE);
LUA->SetField(-2, "DEVICECHANGE");

LUA->PushNumber(WM_PENWINFIRST);
LUA->SetField(-2, "PENWINFIRST");

LUA->PushNumber(WM_MDICREATE);
LUA->SetField(-2, "MDICREATE");

LUA->PushNumber(WM_PENWINLAST);
LUA->SetField(-2, "PENWINLAST");

LUA->PushNumber(WM_MDIDESTROY);
LUA->SetField(-2, "MDIDESTROY");

LUA->PushNumber(WM_POWER);
LUA->SetField(-2, "POWER");

LUA->PushNumber(WM_MDIACTIVATE);
LUA->SetField(-2, "MDIACTIVATE");

LUA->PushNumber(WM_POWERBROADCAST);
LUA->SetField(-2, "POWERBROADCAST");

LUA->PushNumber(WM_MDIRESTORE);
LUA->SetField(-2, "MDIRESTORE");

LUA->PushNumber(WM_PRINT);
LUA->SetField(-2, "PRINT");

LUA->PushNumber(WM_MDINEXT);
LUA->SetField(-2, "MDINEXT");

LUA->PushNumber(WM_PRINTCLIENT);
LUA->SetField(-2, "PRINTCLIENT");

LUA->PushNumber(WM_MDIMAXIMIZE);
LUA->SetField(-2, "MDIMAXIMIZE");

LUA->PushNumber(WM_QUERYDRAGICON);
LUA->SetField(-2, "QUERYDRAGICON");

LUA->PushNumber(WM_MDITILE);
LUA->SetField(-2, "MDITILE");

LUA->PushNumber(WM_QUERYENDSESSION);
LUA->SetField(-2, "QUERYENDSESSION");

LUA->PushNumber(WM_MDICASCADE);
LUA->SetField(-2, "MDICASCADE");

LUA->PushNumber(WM_QUERYNEWPALETTE);
LUA->SetField(-2, "QUERYNEWPALETTE");

LUA->PushNumber(WM_MDIICONARRANGE);
LUA->SetField(-2, "MDIICONARRANGE");

LUA->PushNumber(WM_QUERYOPEN);
LUA->SetField(-2, "QUERYOPEN");

LUA->PushNumber(WM_MDIGETACTIVE);
LUA->SetField(-2, "MDIGETACTIVE");

LUA->PushNumber(WM_QUERYUISTATE);
LUA->SetField(-2, "QUERYUISTATE");

LUA->PushNumber(WM_MDISETMENU);
LUA->SetField(-2, "MDISETMENU");

LUA->PushNumber(WM_QUEUESYNC);
LUA->SetField(-2, "QUEUESYNC");

LUA->PushNumber(WM_ENTERSIZEMOVE);
LUA->SetField(-2, "ENTERSIZEMOVE");

LUA->PushNumber(WM_QUIT);
LUA->SetField(-2, "QUIT");

LUA->PushNumber(WM_EXITSIZEMOVE);
LUA->SetField(-2, "EXITSIZEMOVE");

LUA->PushNumber(WM_RBUTTONDBLCLK);
LUA->SetField(-2, "RBUTTONDBLCLK");

LUA->PushNumber(WM_DROPFILES);
LUA->SetField(-2, "DROPFILES");

LUA->PushNumber(WM_RBUTTONDOWN);
LUA->SetField(-2, "RBUTTONDOWN");

LUA->PushNumber(WM_MDIREFRESHMENU);
LUA->SetField(-2, "MDIREFRESHMENU");

LUA->PushNumber(WM_RBUTTONUP);
LUA->SetField(-2, "RBUTTONUP");

LUA->PushNumber(WM_IME_SETCONTEXT);
LUA->SetField(-2, "IME_SETCONTEXT");

LUA->PushNumber(WM_RENDERALLFORMATS);
LUA->SetField(-2, "RENDERALLFORMATS");

LUA->PushNumber(WM_IME_NOTIFY);
LUA->SetField(-2, "IME_NOTIFY");

LUA->PushNumber(WM_RENDERFORMAT);
LUA->SetField(-2, "RENDERFORMAT");

LUA->PushNumber(WM_IME_CONTROL);
LUA->SetField(-2, "IME_CONTROL");

LUA->PushNumber(WM_SETCURSOR);
LUA->SetField(-2, "SETCURSOR");

LUA->PushNumber(WM_IME_COMPOSITIONFULL);
LUA->SetField(-2, "IME_COMPOSITIONFULL");

LUA->PushNumber(WM_SETFOCUS);
LUA->SetField(-2, "SETFOCUS");

LUA->PushNumber(WM_IME_SELECT);
LUA->SetField(-2, "IME_SELECT");

LUA->PushNumber(WM_SETFONT);
LUA->SetField(-2, "SETFONT");

LUA->PushNumber(WM_IME_CHAR);
LUA->SetField(-2, "IME_CHAR");

LUA->PushNumber(WM_SETHOTKEY);
LUA->SetField(-2, "SETHOTKEY");

LUA->PushNumber(WM_IME_REQUEST);
LUA->SetField(-2, "IME_REQUEST");

LUA->PushNumber(WM_SETICON);
LUA->SetField(-2, "SETICON");

LUA->PushNumber(WM_IME_KEYDOWN);
LUA->SetField(-2, "IME_KEYDOWN");

LUA->PushNumber(WM_SETREDRAW);
LUA->SetField(-2, "SETREDRAW");

LUA->PushNumber(WM_IME_KEYUP);
LUA->SetField(-2, "IME_KEYUP");

LUA->PushNumber(WM_SETTEXT);
LUA->SetField(-2, "SETTEXT");

LUA->PushNumber(WM_MOUSEHOVER);
LUA->SetField(-2, "MOUSEHOVER");

LUA->PushNumber(WM_SETTINGCHANGE);
LUA->SetField(-2, "SETTINGCHANGE");

LUA->PushNumber(WM_MOUSELEAVE);
LUA->SetField(-2, "MOUSELEAVE");

LUA->PushNumber(WM_SHOWWINDOW);
LUA->SetField(-2, "SHOWWINDOW");

LUA->PushNumber(WM_NCMOUSEHOVER);
LUA->SetField(-2, "NCMOUSEHOVER");

LUA->PushNumber(WM_SIZE);
LUA->SetField(-2, "SIZE");

LUA->PushNumber(WM_NCMOUSELEAVE);
LUA->SetField(-2, "NCMOUSELEAVE");

LUA->PushNumber(WM_SIZECLIPBOARD);
LUA->SetField(-2, "SIZECLIPBOARD");

LUA->PushNumber(WM_WTSSESSION_CHANGE);
LUA->SetField(-2, "WTSSESSION_CHANGE");

LUA->PushNumber(WM_SIZING);
LUA->SetField(-2, "SIZING");

LUA->PushNumber(WM_TABLET_FIRST);
LUA->SetField(-2, "TABLET_FIRST");

LUA->PushNumber(WM_SPOOLERSTATUS);
LUA->SetField(-2, "SPOOLERSTATUS");

LUA->PushNumber(WM_TABLET_LAST);
LUA->SetField(-2, "TABLET_LAST");

LUA->PushNumber(WM_STYLECHANGED);
LUA->SetField(-2, "STYLECHANGED");

LUA->PushNumber(WM_CUT);
LUA->SetField(-2, "CUT");

LUA->PushNumber(WM_STYLECHANGING);
LUA->SetField(-2, "STYLECHANGING");

LUA->PushNumber(WM_COPY);
LUA->SetField(-2, "COPY");

LUA->PushNumber(WM_SYNCPAINT);
LUA->SetField(-2, "SYNCPAINT");

LUA->PushNumber(WM_PASTE);
LUA->SetField(-2, "PASTE");

LUA->PushNumber(WM_SYSCHAR);
LUA->SetField(-2, "SYSCHAR");

LUA->PushNumber(WM_CLEAR);
LUA->SetField(-2, "CLEAR");

LUA->PushNumber(WM_SYSCOLORCHANGE);
LUA->SetField(-2, "SYSCOLORCHANGE");

LUA->PushNumber(WM_UNDO);
LUA->SetField(-2, "UNDO");

LUA->PushNumber(WM_SYSCOMMAND);
LUA->SetField(-2, "SYSCOMMAND");

LUA->PushNumber(WM_RENDERFORMAT);
LUA->SetField(-2, "RENDERFORMAT");

LUA->PushNumber(WM_SYSDEADCHAR);
LUA->SetField(-2, "SYSDEADCHAR");

LUA->PushNumber(WM_RENDERALLFORMATS);
LUA->SetField(-2, "RENDERALLFORMATS");

LUA->PushNumber(WM_SYSKEYDOWN);
LUA->SetField(-2, "SYSKEYDOWN");

LUA->PushNumber(WM_DESTROYCLIPBOARD);
LUA->SetField(-2, "DESTROYCLIPBOARD");

LUA->PushNumber(WM_SYSKEYUP);
LUA->SetField(-2, "SYSKEYUP");

LUA->PushNumber(WM_DRAWCLIPBOARD);
LUA->SetField(-2, "DRAWCLIPBOARD");

LUA->PushNumber(WM_TABLET_FIRST);
LUA->SetField(-2, "TABLET_FIRST");

LUA->PushNumber(WM_PAINTCLIPBOARD);
LUA->SetField(-2, "PAINTCLIPBOARD");

LUA->PushNumber(WM_TABLET_LAST);
LUA->SetField(-2, "TABLET_LAST");

LUA->PushNumber(WM_VSCROLLCLIPBOARD);
LUA->SetField(-2, "VSCROLLCLIPBOARD");

LUA->PushNumber(WM_TCARD);
LUA->SetField(-2, "TCARD");

LUA->PushNumber(WM_SIZECLIPBOARD);
LUA->SetField(-2, "SIZECLIPBOARD");

LUA->PushNumber(WM_THEMECHANGED);
LUA->SetField(-2, "THEMECHANGED");

LUA->PushNumber(WM_ASKCBFORMATNAME);
LUA->SetField(-2, "ASKCBFORMATNAME");

LUA->PushNumber(WM_TIMECHANGE);
LUA->SetField(-2, "TIMECHANGE");

LUA->PushNumber(WM_CHANGECBCHAIN);
LUA->SetField(-2, "CHANGECBCHAIN");

LUA->PushNumber(WM_TIMER);
LUA->SetField(-2, "TIMER");

LUA->PushNumber(WM_HSCROLLCLIPBOARD);
LUA->SetField(-2, "HSCROLLCLIPBOARD");

LUA->PushNumber(WM_UNDO);
LUA->SetField(-2, "UNDO");

LUA->PushNumber(WM_QUERYNEWPALETTE);
LUA->SetField(-2, "QUERYNEWPALETTE");

LUA->PushNumber(WM_UNICHAR);
LUA->SetField(-2, "UNICHAR");

LUA->PushNumber(WM_PALETTEISCHANGING);
LUA->SetField(-2, "PALETTEISCHANGING");

LUA->PushNumber(WM_UNINITMENUPOPUP);
LUA->SetField(-2, "UNINITMENUPOPUP");

LUA->PushNumber(WM_PALETTECHANGED);
LUA->SetField(-2, "PALETTECHANGED");

LUA->PushNumber(WM_UPDATEUISTATE);
LUA->SetField(-2, "UPDATEUISTATE");

LUA->PushNumber(WM_HOTKEY);
LUA->SetField(-2, "HOTKEY");

LUA->PushNumber(WM_USER);
LUA->SetField(-2, "USER");

LUA->PushNumber(WM_PRINT);
LUA->SetField(-2, "PRINT");

LUA->PushNumber(WM_USERCHANGED);
LUA->SetField(-2, "USERCHANGED");

LUA->PushNumber(WM_PRINTCLIENT);
LUA->SetField(-2, "PRINTCLIENT");

LUA->PushNumber(WM_VKEYTOITEM);
LUA->SetField(-2, "VKEYTOITEM");

LUA->PushNumber(WM_APPCOMMAND);
LUA->SetField(-2, "APPCOMMAND");

LUA->PushNumber(WM_VSCROLL);
LUA->SetField(-2, "VSCROLL");

LUA->PushNumber(WM_THEMECHANGED);
LUA->SetField(-2, "THEMECHANGED");

LUA->PushNumber(WM_VSCROLLCLIPBOARD);
LUA->SetField(-2, "VSCROLLCLIPBOARD");

LUA->PushNumber(WM_HANDHELDFIRST);
LUA->SetField(-2, "HANDHELDFIRST");

LUA->PushNumber(WM_WINDOWPOSCHANGED);
LUA->SetField(-2, "WINDOWPOSCHANGED");

LUA->PushNumber(WM_HANDHELDLAST);
LUA->SetField(-2, "HANDHELDLAST");

LUA->PushNumber(WM_WINDOWPOSCHANGING);
LUA->SetField(-2, "WINDOWPOSCHANGING");

LUA->PushNumber(WM_AFXFIRST);
LUA->SetField(-2, "AFXFIRST");

LUA->PushNumber(WM_WININICHANGE);
LUA->SetField(-2, "WININICHANGE");

LUA->PushNumber(WM_AFXLAST);
LUA->SetField(-2, "AFXLAST");

LUA->PushNumber(WM_WTSSESSION_CHANGE);
LUA->SetField(-2, "WTSSESSION_CHANGE");

LUA->PushNumber(WM_PENWINFIRST);
LUA->SetField(-2, "PENWINFIRST");

LUA->PushNumber(WM_XBUTTONDBLCLK);
LUA->SetField(-2, "XBUTTONDBLCLK");

LUA->PushNumber(WM_PENWINLAST);
LUA->SetField(-2, "PENWINLAST");

LUA->PushNumber(WM_XBUTTONDOWN);
LUA->SetField(-2, "XBUTTONDOWN");

LUA->PushNumber(WM_USER);
LUA->SetField(-2, "USER");

LUA->PushNumber(WM_XBUTTONUP);
LUA->SetField(-2, "XBUTTONUP");

LUA->PushNumber(WM_APP);
LUA->SetField(-2, "APP");
